version: "3.9"

services:
    db:
        image: mysql:5.7
        volumes:
            - /var/lib/mysql
        restart: always
        environment:
            MYSQL_USER: admin
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_PASSWORD: admin
            MYSQL_DATABASE: graduation-db
        ports:
            - "3306:3306"

    adminer:
        image: adminer
        restart: always
        depends_on: 
            - db
        ports:
            - "8080:8080"